#!/usr/bin/env python3
"""
Main entry point for the cryptocurrency analysis system.
Scheduled execution:
- SaucerSwap token scraper: runs every 30 seconds
- Sonefi.xyz memeLaunch scraper: runs every 15 minutes
- Twitter scraper + Gemini analysis: runs every hour (independent of token updates)
"""
import asyncio
import logging
import os
import json
import time
from datetime import datetime, timedelta
from playwright.async_api import async_playwright

# Import components from our module
from scraper import main as run_token_scraper, scrape_sonefi_memeLaunch
from twitter import scrape_twitter_for_coins
from gemini_analyzer import analyze_sentiment_with_gemini

# Configure logging
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(SCRIPT_DIR, "data")
LOG_DIR = SCRIPT_DIR  # Keep logs in main directory
LOG_FILE = os.path.join(LOG_DIR, "crypto_analysis.log")

# Create data directory if it doesn't exist
os.makedirs(DATA_DIR, exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler(LOG_FILE),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger("main")

# Scheduling intervals
SAUCERSWAP_INTERVAL = 30  # 30 seconds between SaucerSwap scraper runs
SONEFI_INTERVAL = 900     # 15 minutes between Sonefi scraper runs
TWITTER_INTERVAL = 3600   # 1 hour between Twitter scraper runs

async def run_saucerswap_scraper():
    """Run the SaucerSwap token scraper and return the token data"""
    try:
        logger.info("Running SaucerSwap token scraper...")
        token_data = await run_token_scraper(headless=True, output_dir=DATA_DIR)
        logger.info(f"Token scraper complete. Found {len(token_data)} tokens")
        return token_data
    except Exception as e:
        logger.error(f"Error in SaucerSwap scraper: {e}", exc_info=True)
        return None

async def run_sonefi_scraper():
    """Run the Sonefi memeLaunch scraper and return the token data"""
    try:
        logger.info("Running Sonefi memeLaunch scraper...")
        
        async with async_playwright() as p:
            browser = await p.chromium.launch(headless=True)
            context = await browser.new_context(viewport={"width": 1366, "height": 768})
            page = await context.new_page()
            
            # Scrape 4 pages of the Sonefi memeLaunch section
            tokens = await scrape_sonefi_memeLaunch(page, max_pages=4)
            
            await browser.close()
            
            # Save the tokens to a specific file
            sonefi_file = os.path.join(DATA_DIR, "sonefi_tokens.json")
            with open(sonefi_file, 'w', encoding='utf-8') as f:
                json.dump(tokens, f, indent=2)
            
            logger.info(f"Sonefi scraper complete. Found {len(tokens)} tokens")
            return tokens
            
    except Exception as e:
        logger.error(f"Error in Sonefi memeLaunch scraper: {e}", exc_info=True)
        return None

async def run_twitter_and_analysis():
    """Run the Twitter scraper and then the Gemini analysis"""
    try:
        logger.info("Running Twitter scraper...")
        twitter_success = await scrape_twitter_for_coins()
        
        if not twitter_success:
            logger.error("Twitter scraper encountered errors. Check twitter_scraper.log for details")
            return False
        
        logger.info("Twitter scraper complete. Checking analysis results...")
        
        # Check if analysis results are available (generated by the Twitter scraper's analyze_coin_data function)
        analysis_file = os.path.join(DATA_DIR, "coin_investment_analysis.json")
        if os.path.exists(analysis_file):
            try:
                with open(analysis_file, 'r', encoding='utf-8') as f:
                    analysis_data = json.load(f)
                
                # Print summary of top coins
                top_coins = analysis_data.get("top_investment_coins", [])
                logger.info(f"Analysis identified {len(top_coins)} top investment opportunities")
                
                print("\n===== TOP INVESTMENT OPPORTUNITIES =====")
                for i, coin in enumerate(top_coins[:5], 1):  # Show top 5
                    print(f"{i}. {coin['symbol']} - Score: {coin.get('investment_score', 0):.2f}")
                print("======================================\n")
                
                return True
            except Exception as e:
                logger.error(f"Error reading analysis results: {e}")
                return False
        else:
            logger.warning("No analysis results found. The analysis may have failed")
            return False
            
    except Exception as e:
        logger.error(f"Error in Twitter scraper and analysis: {e}", exc_info=True)
        return False

async def scheduled_execution():
    """
    Run components on scheduled intervals:
    - SaucerSwap scraper: every 30 seconds
    - Sonefi memeLaunch scraper: every 15 minutes
    - Twitter scraper + Gemini analysis: every hour (independent of token updates)
    """
    logger.info("Starting scheduled execution")
    print("Cryptocurrency analysis pipeline is now running on schedule:")
    print(f"- SaucerSwap scraper: every {SAUCERSWAP_INTERVAL} seconds")
    print(f"- Sonefi memeLaunch scraper: every {SONEFI_INTERVAL/60} minutes")
    print(f"- Twitter scraper + Gemini analysis: every {TWITTER_INTERVAL/3600} hour(s)")
    print(f"- All JSON files will be stored in: {DATA_DIR}")
    
    # Set up independent timers for each component
    next_saucerswap_run = datetime.now()
    next_sonefi_run = datetime.now()
    next_twitter_run = datetime.now() + timedelta(seconds=TWITTER_INTERVAL)
    
    while True:
        current_time = datetime.now()
        
        # Check if it's time to run the SaucerSwap scraper
        if current_time >= next_saucerswap_run:
            await run_saucerswap_scraper()
            next_saucerswap_run = current_time + timedelta(seconds=SAUCERSWAP_INTERVAL)
        
        # Check if it's time to run the Sonefi memeLaunch scraper
        if current_time >= next_sonefi_run:
            await run_sonefi_scraper()
            next_sonefi_run = current_time + timedelta(seconds=SONEFI_INTERVAL)
        
        # Check if it's time to run the Twitter scraper (independently)
        if current_time >= next_twitter_run:
            logger.info(f"Running scheduled Twitter scraper and analysis at {current_time.isoformat()}")
            await run_twitter_and_analysis()
            next_twitter_run = current_time + timedelta(seconds=TWITTER_INTERVAL)
            logger.info(f"Next Twitter run scheduled for {next_twitter_run.isoformat()}")
        
        # Calculate time until next runs
        time_until_next_saucerswap = (next_saucerswap_run - datetime.now()).total_seconds()
        time_until_next_sonefi = (next_sonefi_run - datetime.now()).total_seconds()
        time_until_next_twitter = (next_twitter_run - datetime.now()).total_seconds()
        
        # Wait until the next task that needs to run (whichever comes first)
        sleep_time = min(
            max(0.1, time_until_next_saucerswap),  # Ensure positive sleep time
            max(0.1, time_until_next_sonefi),      # Ensure positive sleep time
            max(0.1, time_until_next_twitter)      # Ensure positive sleep time
        )
        
        # Log next scheduled runs
        logger.debug(f"Next SaucerSwap run in {time_until_next_saucerswap:.1f} seconds")
        logger.debug(f"Next Sonefi run in {time_until_next_sonefi:.1f} seconds")
        logger.debug(f"Next Twitter run in {time_until_next_twitter:.1f} seconds")
        
        # Sleep until the next task needs to run
        await asyncio.sleep(sleep_time)

async def main():
    """
    Main function that starts the scheduled execution
    """
    start_time = datetime.now()
    logger.info(f"Starting cryptocurrency analysis pipeline at {start_time.isoformat()}")
    
    try:
        # Initial run of SaucerSwap scraper
        await run_saucerswap_scraper()
        
        # Initial run of Sonefi memeLaunch scraper
        logger.info("Running initial Sonefi memeLaunch scraper...")
        await run_sonefi_scraper()
        
        # Initial run of Twitter scraper and analysis
        logger.info("Running initial Twitter scraper and analysis...")
        await run_twitter_and_analysis()
        
        # Start scheduled execution with independent timers
        logger.info("Starting scheduled execution with independent timers")
        await scheduled_execution()
        
    except KeyboardInterrupt:
        logger.info("Stopping cryptocurrency analysis pipeline due to user interrupt")
        print("\nStopping cryptocurrency analysis pipeline. Goodbye!")
    except Exception as e:
        logger.error(f"Error in cryptocurrency analysis pipeline: {e}", exc_info=True)
        print(f"Error: {e}")
        print(f"Check log file for details: {LOG_FILE}")

if __name__ == "__main__":
    print("Starting cryptocurrency analysis pipeline with scheduled execution...")
    asyncio.run(main())